{
 "title": "00. KPIs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "rpl", "query": "5,15,60,1440,10080" }
  ]
 },
 "panels": [
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pokemon scanned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(Datetime,$__interval) as 'time',\r\n  sum(totMon) AS \"Pokemon scanned\",\r\n  100*sum(ivMon)/sum(totMon) AS '% IV',\r\n  (sum(encSecLeft)/sum(verifiedEnc))/60 AS \"Despawn Minutes Left\",\r\n  sum(encTth25to30)/(sum(encTthMax5)+sum(encTth5to10)+sum(encTth10to15)+sum(encTth15to20)+sum(encTth20to25)+sum(encTth25to30)) AS \"25_to_30\",\r\n  sum(encTth20to25)/(sum(encTthMax5)+sum(encTth5to10)+sum(encTth10to15)+sum(encTth15to20)+sum(encTth20to25)+sum(encTth25to30)) AS \"20_to_25\",\r\n  sum(encTth15to20)/(sum(encTthMax5)+sum(encTth5to10)+sum(encTth10to15)+sum(encTth15to20)+sum(encTth20to25)+sum(encTth25to30)) AS \"15_to_20\",\r\n  sum(encTth10to15)/(sum(encTthMax5)+sum(encTth5to10)+sum(encTth10to15)+sum(encTth15to20)+sum(encTth20to25)+sum(encTth25to30)) AS \"10_to_15\",\r\n  sum(encTth5to10)/(sum(encTthMax5)+sum(encTth5to10)+sum(encTth10to15)+sum(encTth15to20)+sum(encTth20to25)+sum(encTth25to30)) AS \"5_to_10\",\r\n  sum(encTthMax5)/(sum(encTthMax5)+sum(encTth5to10)+sum(encTth10to15)+sum(encTth15to20)+sum(encTth20to25)+sum(encTth25to30)) AS \"below_5\"\r\nFROM stats_mon_area\r\nWHERE\r\n  $__timeFilter(datetime) and\r\n  rpl = '$rpl'\r\nGROUP BY 1\r\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Despawn time left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "panelId": 1 }
   ]
  },
  {
   "title": "Quest scanned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(Datetime,$__interval) as 'time',\r\n  100*sum(ARcum)/sum(stops) as '%AR quest scanned',\r\n  100*sum(nonARcum)/sum(stops) as '%nonAR quest scanned'\r\nFROM stats_quest_area\r\nWHERE\r\n  $__timeFilter(datetime)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  { "title": "Bit more detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Proto handling time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(Datetime,$__interval) as 'time',\r\n  avgTime as 'Invasion workers'\r\n\r\nFROM stats_invasion\r\nWHERE\r\n  $__timeFilter(datetime) and\r\n  RPL = '$rpl' \r\nGROUP BY 1\r\nORDER BY $__timeGroup(Datetime,$__interval)"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroup(Datetime,$__interval) as 'time',\r\n  sum(totalProtoTimeFort)/sum(modeLocations) as 'Fort workers'\r\n\r\nFROM stats_worker_fort\r\nWHERE\r\n  $__timeFilter(datetime) and\r\n  RPL = '$rpl'\r\nGROUP BY 1\r\nORDER BY $__timeGroup(Datetime,$__interval)"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroup(Datetime,$__interval) as 'time',\r\n  1000*sum(timeElapsed)/sum(loc_count) as 'Area workers'\r\n\r\nFROM stats_worker\r\nWHERE\r\n  $__timeFilter(datetime) and\r\n  RPL = '$rpl' \r\nGROUP BY 1\r\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Area mode: gmo repeated attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Area mode: gmo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n$__timeGroup(datetime,$__interval) AS \"time\",\r\nsum(gmoGivingUp) as 'GMO - giving up',\r\n100*sum(gmoInitialSuccess)/sum(loc_count) as 'initial GMO success rate',\r\n100*sum(gmoGivingUp)/sum(loc_count) as 'GMO failure rate 8/8',\r\n(sum(gmo0fail)-sum(gmo1fail))/sum(gmo0fail) as 'GMO success after retry #1',\r\n(sum(gmo1fail)-sum(gmo2fail))/sum(gmo0fail) as '#2',\r\n(sum(gmo2fail)-sum(gmo3fail))/sum(gmo0fail) as '#3',\r\n(sum(gmo3fail)-sum(gmo4fail))/sum(gmo0fail) as '#4',\r\n(sum(gmo4fail)-sum(gmo5fail))/sum(gmo0fail) as '#5',\r\n(sum(gmo5fail)-sum(gmo6fail))/sum(gmo0fail) as '#6',\r\n(sum(gmo6fail)-sum(gmo7fail))/sum(gmo0fail) as '#7',\r\n(sum(gmo7fail)-sum(gmo8fail))/sum(gmo0fail) as '#8'\r\n\r\nFROM stats_worker\r\n\r\nWHERE\r\n$__timeFilter(Datetime) and\r\n-- Datetime BETWEEN '${__from:date:iso}' AND '${__to:date:iso}' and\r\nRPL='$rpl'\r\nGROUP BY 1  \r\nORDER BY $__timeGroup(datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Despawn minutes left details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "panelId": 1 }
   ]
  },
  {
   "title": "All modes, rpc errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(a.datetime, $__interval) AS \"time\",\r\n  ifnull(a.rpc4,0) + ifnull(c.rpc4,0) + ifnull(d.rpc4,0) as 'rpc4',\r\n  ifnull(a.rpc5,0) + ifnull(c.rpc5,0) + ifnull(d.rpc5,0) as 'rpc5',\r\n  ifnull(a.rpc6,0) + ifnull(c.rpc6,0) + ifnull(d.rpc6,0) as 'rpc6',\r\n  ifnull(a.rpc7,0) + ifnull(c.rpc7,0) + ifnull(d.rpc7,0) as 'rpc7',\r\n  ifnull(a.rpc8,0) + ifnull(c.rpc8,0) + ifnull(d.rpc8,0) as 'rpc8',\r\n  ifnull(a.rpc9,0) + ifnull(c.rpc9,0) + ifnull(d.rpc9,0) as 'rpc9',\r\n  ifnull(a.rpc11,0) + ifnull(c.rpc11,0) + ifnull(d.rpc11,0) as 'rpc11',\r\n  ifnull(a.rpc12,0) + ifnull(c.rpc12,0) + ifnull(d.rpc12,0) as 'rpc12',\r\n  ifnull(a.rpc13,0) + ifnull(c.rpc13,0) + ifnull(d.rpc13,0) as 'rpc13',\r\n  ifnull(a.rpc14,0) + ifnull(c.rpc14,0) + ifnull(d.rpc14,0) as 'rpc14',\r\n  ifnull(a.rpc15,0) + ifnull(c.rpc15,0) + ifnull(d.rpc15,0) as 'rpc15',\r\n  ifnull(a.rpc16,0) + ifnull(c.rpc16,0) + ifnull(d.rpc16,0) as 'rpc16',\r\n  ifnull(a.rpc17,0) + ifnull(c.rpc17,0) + ifnull(d.rpc17,0) as 'rpc17',\r\n  ifnull(a.rpc18,0) + ifnull(c.rpc18,0) + ifnull(d.rpc18,0) as 'rpc18',\r\n  ifnull(a.swTotal,0)+ifnull(c.swTotal,0)+ifnull(d.swTotal,0) as 'Accounts rotated',\r\n  ifnull(a.swWarnSusp,0)+ifnull(c.swWarnSusp,0)+ifnull(d.swWarnSusp,0) as 'Warned',\r\n  ifnull(a.swBanned,0)+ifnull(c.swBanned,0)+ifnull(d.swBanned,0) as 'Banned',\r\n  ifnull(a.swDisabled,0)+ifnull(c.swDisabled,0)+ifnull(d.swDisabled,0) as 'Disabled',\r\n  ifnull(a.swDayLimit,0)+ifnull(c.swDayLimit,0)+ifnull(d.swDayLimit,0) as 'Daily limit',\r\n  ifnull(a.swRange,0)+ifnull(c.swRange,0)+ifnull(d.swRange,0) as 'Out of range 10 times',\r\n  ifnull(a.swTime,0)+ifnull(c.swTime,0)+ifnull(d.swTime,0) as 'Max connection time',\r\n  ifnull(a.swStop,0)+ifnull(c.swStop,0)+ifnull(d.swStop,0) as 'Stop cooldown',\r\n  ifnull(a.swLLapi,0)+ifnull(c.swLLapi,0)+ifnull(d.swLLapi,0) as 'LLapi',\r\n  ifnull(a.swQdist,0)+ifnull(c.swQdist,0)+ifnull(d.swQdist,0) as 'Quest distance',\r\n  ifnull(a.backoff,0)+ifnull(c.backoff,0)+ifnull(d.backoff,0) as 'backoff'\r\nFROM\r\n  dragoLog a\r\n  LEFT JOIN dragoLog_invasion c ON a.datetime = c.datetime\r\n  and a.rpl = c.rpl\r\n  LEFT JOIN dragoLog_fort d ON a.datetime = d.datetime\r\n  and a.rpl = d.rpl\r\nWHERE\r\n  $__timeFilter(a.Datetime) and\r\n  a.RPL = '$rpl'\r\nGROUP BY 1\r\nORDER BY $__timeGroup(a.datetime, $__interval)"
    }
   ]
  },
  {
   "title": "account switch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Consecutive disabled status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(Datetime,$__interval) as 'time',\r\n  consecDis1 as 'Consecutive disabled <= 1',\r\n  consecDis2 as 'Consecutive disabled = 2',\r\n  consecDis3 as 'Consecutive disabled = 3',\r\n  consecDis4p as 'Consecutive disabled >= 4'\r\nFROM accounts\r\nGROUP BY 1\r\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  }
 ]
}