{
 "title": "10. Dragonite log",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "RPL",
    "query": "select distinct(rpl) from dragoLog"
   }
  ]
 },
 "panels": [
  { "title": "Generic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "account re-use warning/available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Pokemon changed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "auth/login",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "total auth time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "remote auth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "remote auth time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "background token requests (initer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "background token request time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "background token refresh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "token cleared",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "background token refresh attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "background token refresh failure rate (ar ban?)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "mitm errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "mitm connection error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "proxy ptc ip banned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  { "title": "All modes combined", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "account switch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "rpc errors (1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "account disconnect < 20s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "rpc erros (2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "rawSql": "SELECT\r\n$__timeGroup(a.datetime,$__interval) AS \"time\",\r\nifnull(a.rpc4,0)+ifnull(c.rpc4,0)+ifnull(d.rpc4,0) as 'rpc4',\r\nifnull(a.rpc5,0)+ifnull(c.rpc5,0)+ifnull(d.rpc5,0) as 'rpc5',\r\nifnull(a.rpc6,0)+ifnull(c.rpc6,0)+ifnull(d.rpc6,0) as 'rpc6',\r\nifnull(a.rpc7,0)+ifnull(c.rpc7,0)+ifnull(d.rpc7,0) as 'rpc7',\r\nifnull(a.rpc8,0)+ifnull(c.rpc8,0)+ifnull(d.rpc8,0) as 'rpc8',\r\nifnull(a.rpc9,0)+ifnull(c.rpc9,0)+ifnull(d.rpc9,0) as 'rpc9',\r\nifnull(a.rpc11,0)+ifnull(c.rpc11,0)+ifnull(d.rpc11,0) as 'rpc11',\r\nifnull(a.rpc12,0)+ifnull(c.rpc12,0)+ifnull(d.rpc12,0) as 'rpc12',\r\nifnull(a.rpc13,0)+ifnull(c.rpc13,0)+ifnull(d.rpc13,0) as 'rpc13',\r\nifnull(a.rpc14,0)+ifnull(c.rpc14,0)+ifnull(d.rpc14,0) as 'rpc14',\r\nifnull(a.rpc15,0)+ifnull(c.rpc15,0)+ifnull(d.rpc15,0) as 'rpc15',\r\nifnull(a.rpc16,0)+ifnull(c.rpc16,0)+ifnull(d.rpc16,0) as 'rpc16',\r\nifnull(a.rpc17,0)+ifnull(c.rpc17,0)+ifnull(d.rpc17,0) as 'rpc17',\r\nifnull(a.rpc18,0)+ifnull(c.rpc18,0)+ifnull(d.rpc18,0) as 'rpc18',\r\nifnull(a.wsError,0) as 'ws error',\r\nifnull(a.wsClose,0) as 'ws closed',\r\nifnull(a.wsMitmRecon,0) as 'mitm initiated reconnect',\r\nifnull(a.mitm500,0) as 'unknown error',\r\nifnull(a.mitm501,0) as 'retry later',\r\nifnull(a.mitm502,0) as 'worker stopped',\r\nifnull(a.mitm503,0) as 'reconnect',\r\nifnull(a.mitmLoginErr,0) as 'total login error',\r\nifnull(a.proxyBan,0) as 'proxy 3h ptc login ban',\r\nifnull(a.authReq,0) as 'Requesting auth',\r\nifnull(a.login,0) as 'Login successful',\r\nifnull(a.swTotal,0)+ifnull(c.swTotal,0)+ifnull(d.swTotal,0) as 'Accounts rotated',\r\nifnull(a.swWarnSusp,0)+ifnull(c.swWarnSusp,0)+ifnull(d.swWarnSusp,0) as 'Warned',\r\nifnull(a.swBanned,0)+ifnull(c.swBanned,0)+ifnull(d.swBanned,0) as 'Banned',\r\nifnull(a.swSbanned,0)+ifnull(c.swSbanned,0)+ifnull(d.swSbanned,0) as 'Shadow Banned',\r\nifnull(a.swDisabled,0)+ifnull(c.swDisabled,0)+ifnull(d.swDisabled,0) as 'Disabled',\r\nifnull(a.swDayLimit,0)+ifnull(c.swDayLimit,0)+ifnull(d.swDayLimit,0) as 'Daily limit',\r\nifnull(a.swRange,0)+ifnull(c.swRange,0)+ifnull(d.swRange,0) as 'Out of range 10 times',\r\nifnull(a.swTime,0)+ifnull(c.swTime,0)+ifnull(d.swTime,0) as 'Max connection time',\r\nifnull(a.swStop,0)+ifnull(c.swStop,0)+ifnull(d.swStop,0) as 'Stop cooldown',\r\nifnull(a.swLLapi,0)+ifnull(c.swLLapi,0)+ifnull(d.swLLapi,0) as 'LLapi',\r\nifnull(a.swQdist,0)+ifnull(c.swQdist,0)+ifnull(d.swQdist,0) as 'Quest distance',\r\nifnull(a.swConsecRPC,0)+ifnull(c.swConsecRPC,0)+ifnull(d.swConsecRPC,0) as 'consecRPC',\r\nifnull(a.backoff,0)+ifnull(c.backoff,0)+ifnull(d.backoff,0) as 'backoff',\r\nifnull(a.noAccount,0) as 'No accounts available',\r\nifnull(a.released24h,0) as 'released less then 24 hours ago',\r\nifnull(a.released7d,0) as 'released less then 7 days ago',\r\nifnull(a.minAuthT,0) as 'minimum auth time',\r\nifnull(a.maxAuthT,0) as 'maximum auth time',\r\nifnull(a.avgAuthT,0) as 'average auth time',\r\nifnull(a.monchange,0) as 'Pokemon changed',\r\nifnull(a.totRemoteAuth,0) as '#total remote auth',\r\nifnull(a.failRemoteAuth,0) as '#failed remote auth',\r\nifnull(a.faultyRemoteAuth,0) as '#faulty remote auth',\r\nifnull(a.minRemoteAuthT,0) as 'minimum remote auth time',\r\nifnull(a.maxRemoteAuthT,0) as 'maximum remote auth time',\r\nifnull(a.avgRemoteAuthT,0) as 'avgerage remote auth time',\r\nifnull(a.lowDuration,0)+ifnull(c.lowDuration,0)+ifnull(d.lowDuration,0) as 'lowDuration',\r\nifnull(bgRefreshSuc,0) as 'background refresh success',\r\nifnull(bgRefreshFail,0) as 'background refresh failure',\r\nifnull(bgRefreshFail,0)+ifnull(bgRefreshSuc,0) as 'background refresh attempts',\r\n100*ifnull(bgRefreshFail,0)/(ifnull(bgRefreshFail,0)+ifnull(bgRefreshSuc,0)) as 'background failure rate',\r\nifnull(bTokenReq,0) as 'background token requests',\r\nifnull(bTokenSuc,0) as 'background token success',\r\nifnull(bTokenMin,0) as 'minimum background token request time',\r\nifnull(bTokenMax,0) as 'maximum background token requests time',\r\nifnull(bTokenAvg,0) as 'average background token requeststime',\r\n100*bTokenSuc/bTokenReq as 'background token successrate',\r\nifnull(tokenCleared,0) as 'token cleared'\r\n\r\nFROM dragoLog a\r\nLEFT JOIN dragoLog_invasion c ON a.datetime=c.datetime and a.rpl=c.rpl\r\nLEFT JOIN dragoLog_fort d ON a.datetime=d.datetime and a.rpl=d.rpl \r\nWHERE\r\na.RPL='$RPL'\r\nGROUP BY 1  \r\nORDER BY $__timeGroup(a.datetime,$__interval)"
    }
   ]
  },
  {
   "title": "rpc errors (3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Area mode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "account switch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "targets": [
      { "panelId": 24 }
     ]
    },
    {
     "title": "rpc errors (1)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "targets": [
      { "panelId": 24 }
     ]
    },
    {
     "title": "account switch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
     "targets": [
      { "panelId": 24 }
     ]
    },
    {
     "title": "area rpc erros (2)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
     "targets": [
      {
       "rawSql": "SELECT\r\n$__timeGroup(datetime,$__interval) AS \"time\",\r\nrpc4,rpc5,rpc6,rpc7,rpc8,rpc9,rpc11,rpc12,rpc13,rpc14,rpc15,rpc16,rpc17,rpc18,\r\n-- noGMO as 'GMO - giving up',\r\n-- gmoPoke as 'Got a GMO: x pokemon',\r\n-- 100*(gmoPoke-gmo0+gmo8)/gmoPoke as 'initial GMO success rate',\r\n-- 100*gmo8/(gmoPoke+gmo8) as 'GMO failure rate 8/8',\r\n-- (gmo0-gmo1)/gmo0 as 'GMO success after retry #1',\r\n-- (gmo1-gmo2)/gmo0 as '#2',\r\n-- (gmo2-gmo3)/gmo0 as '#3',\r\n-- (gmo3-gmo4)/gmo0 as '#4',\r\n-- (gmo4-gmo5)/gmo0 as '#5',\r\n-- (gmo5-gmo6)/gmo0 as '#6',\r\n-- (gmo6-gmo7)/gmo0 as '#7',\r\n-- (gmo7-gmo8)/gmo0 as '#8',\r\n-- gmo0+gmo1+gmo2+gmo3+gmo4+gmo5+gmo6+gmo7 as 'total retry',\r\nifnull(swTotal,0) as 'Accounts rotated',\r\nifnull(swWarnSusp,0) as 'Warned',\r\nifnull(swBanned,0) as 'Banned',\r\nifnull(swSbanned,0) as 'Shadow banned',\r\nifnull(swDisabled,0) as 'Disabled',\r\nifnull(swDayLimit,0) as 'Daily limit',\r\nifnull(swRange,0) as 'Out of range 10 times',\r\nifnull(swTime,0) as 'Max connection time',\r\nifnull(swStop,0) as 'Stop cooldown',\r\nifnull(swLLapi,0) as 'LLapi',\r\nifnull(swQdist,0) as 'Quest distance',\r\nifnull(swConsecRPC,0) as 'consecRPC',\r\nbackoff,\r\nifnull(lowDuration,0) as 'lowDuration'\r\nFROM dragoLog\r\n\r\nWHERE\r\nRPL='$RPL'\r\nGROUP BY 1  \r\nORDER BY $__timeGroup(datetime,$__interval)"
      }
     ]
    },
    {
     "title": "rpc errors (3)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
     "targets": [
      { "panelId": 24 }
     ]
    }
   ]
  },
  {
   "title": "Invasion workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "account switch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "targets": [
      { "panelId": 44 }
     ]
    },
    {
     "title": "rpc errors (1)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "targets": [
      { "panelId": 44 }
     ]
    },
    {
     "title": "account switchaccount disconnect < 20s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "targets": [
      { "panelId": 44 }
     ]
    },
    {
     "title": "invasion rpc erros (2)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "targets": [
      {
       "rawSql": "SELECT\r\n$__timeGroup(datetime,$__interval) AS \"time\",\r\nrpc4,rpc5,rpc6,rpc7,rpc8,rpc9,rpc11,rpc12,rpc13,rpc14,rpc15,rpc16,rpc17,rpc18,\r\nifnull(swTotal,0) as 'Accounts rotated',\r\nifnull(swWarnSusp,0) as 'Warned',\r\nifnull(swBanned,0) as 'Banned',\r\nifnull(swSbanned,0) as 'Shadow banned',\r\nifnull(swDisabled,0) as 'Disabled',\r\nifnull(swDayLimit,0) as 'Daily limit',\r\nifnull(swRange,0) as 'Out of range 10 times',\r\nifnull(swTime,0) as 'Max connection time',\r\nifnull(swStop,0) as 'Stop cooldown',\r\nifnull(swQdist,0) as 'Quest distance',\r\nifnull(swLLapi,0) as 'LLapi',\r\nifnull(swConsecRPC,0) as 'consecRPC',\r\nbackoff,\r\nifnull(lowDuration,0) as 'lowDuration'\r\nFROM dragoLog_invasion\r\n\r\nWHERE\r\nRPL='$RPL'\r\nGROUP BY 1  \r\nORDER BY $__timeGroup(datetime,$__interval)"
      }
     ]
    },
    {
     "title": "rpc errors (3)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
     "targets": [
      { "panelId": 44 }
     ]
    }
   ]
  },
  {
   "title": "Fort workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "account switch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "targets": [
      { "panelId": 45 }
     ]
    },
    {
     "title": "rpc errors (1)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "targets": [
      { "panelId": 45 }
     ]
    },
    {
     "title": "account disconnect < 20s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "targets": [
      { "panelId": 45 }
     ]
    },
    {
     "title": "fort rpc erros (2)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "targets": [
      {
       "rawSql": "SELECT\r\n$__timeGroup(datetime,$__interval) AS \"time\",\r\nrpc4,rpc5,rpc6,rpc7,rpc8,rpc9,rpc11,rpc12,rpc13,rpc14,rpc15,rpc16,rpc17,rpc18,\r\n-- noGMO as 'GMO - giving up',\r\n-- gmoPoke as 'Got a GMO: x pokemon',\r\n-- 100*(gmoPoke-gmo0+gmo8)/gmoPoke as 'initial GMO success rate',\r\n-- 100*gmo8/(gmoPoke+gmo8) as 'GMO failure rate 8/8',\r\n-- (gmo0-gmo1)/gmo0 as 'GMO success after retry #1',\r\n-- (gmo1-gmo2)/gmo0 as '#2',\r\n-- (gmo2-gmo3)/gmo0 as '#3',\r\n-- (gmo3-gmo4)/gmo0 as '#4',\r\n-- (gmo4-gmo5)/gmo0 as '#5',\r\n-- (gmo5-gmo6)/gmo0 as '#6',\r\n-- (gmo6-gmo7)/gmo0 as '#7',\r\n-- (gmo7-gmo8)/gmo0 as '#8',\r\n-- gmo0+gmo1+gmo2+gmo3+gmo4+gmo5+gmo6+gmo7 as 'total retry',\r\nifnull(swTotal,0) as 'Accounts rotated',\r\nifnull(swWarnSusp,0) as 'Warned',\r\nifnull(swBanned,0) as 'Banned',\r\nifnull(swSbanned,0) as 'Shadow banned',\r\nifnull(swDisabled,0) as 'Disabled',\r\nifnull(swDayLimit,0) as 'Daily limit',\r\nifnull(swRange,0) as 'Out of range 10 times',\r\nifnull(swTime,0) as 'Max connection time',\r\nifnull(swStop,0) as 'Stop cooldown',\r\nifnull(swQdist,0) as 'Quest distance',\r\nifnull(swLLapi,0) as 'LLapi',\r\nifnull(swConsecRPC,0) as 'consecRPC',\r\nbackoff,\r\nifnull(lowDuration,0) as 'lowDuration'\r\nFROM dragoLog_fort\r\n\r\nWHERE\r\nRPL='$RPL'\r\nGROUP BY 1  \r\nORDER BY $__timeGroup(datetime,$__interval)"
      }
     ]
    },
    {
     "title": "rpc errors (3)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "targets": [
      { "panelId": 45 }
     ]
    }
   ]
  }
 ]
}